-- Services table for Supabase
-- Run in Supabase SQL Editor

create extension if not exists pgcrypto;

create table if not exists public.services (
  id uuid primary key default gen_random_uuid(),
  service_id bigint generated by default as identity unique,
  name text not null,
  description text not null,
  category text not null check (
    category in ('installation', 'fabrication', 'consultation', 'maintenance', 'custom')
  ),
  status text not null default 'active' check (
    status in ('active', 'inactive', 'draft', 'archived')
  ),
  image_url text not null,
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_services_updated_at on public.services;
create trigger trg_services_updated_at
before update on public.services
for each row
execute function public.set_updated_at();

-- Optional for quick local testing with anon key:
-- alter table public.services disable row level security;
